apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo
    tier: frontend
    environment: production
spec:
  containers:
  - name: demo-app-container
    image: demo-app-image:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: demo-volume
      mountPath: /app/data
    env:
    - name: ENVIRONMENT
      value: "production"
  volumes:
  - name: demo-volume
    persistentVolumeClaim:
      claimName: demo-pvc