apiVersion: v1
kind: Pod
metadata:
  name: demo-app-pod
  labels:
    app: demo
    tier: frontend
    environment: production
spec:
  containers:
  - name: demo-app-container
    image: demo-app-image:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    env:
    - name: ENVIRONMENT
      value: "production"